-keepclassmembers class com.autobrowse.android.data.remote.** { *; }
-keep class com.autobrowse.android.data.remote.** { *; }
-keep class com.llamatik.library.platform.** { *; }
-keep class io.noties.markwon.** { *; }
-keep class ru.noties.jlatexmath.** { *; }
-dontwarn org.scilab.forge.jlatexmath.**
-dontwarn com.caverock.androidsvg.**
-dontwarn pl.droidsonroids.gif.**
-dontwarn com.google.errorprone.annotations.**